name: "Get & Cache Dependencies"
description: "Get dependencies with NPM and cache them for future use"
runs:
  using: "composite"
  steps:
    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
